<?php

namespace AppBundle\Repository;

/**
 * User_detailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_detailsRepository extends \Doctrine\ORM\EntityRepository
{
}
